### ISSUE TITLE
Note do not add access keys / tokens to a public repo

### ISSUE THREAD

**Issue by AubreyHewes** [lurnid/react-static-contentful#1]
Use env injection

i.e.

CDAPI_ACCESS_TOKEN = process.env.CDAPI_ACCESS_TOKEN

For development/build you can add `dotenv` to your static config to load a non repo `.env` file. Removing the need to set the env for every invocation.

**Comment by lurnid** [comment]
I used a 'throwaway' Contentful space when putting the example together so the token isn't valid. But you're right that I should have followed best practice in any case. Will update the repo accordingly

**Comment by AubreyHewes** [comment]
:+1:
